# Generated by Django 4.2.1 on 2023-08-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_usertext_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertext',
            name='message',
            field=models.TextField(max_length=1000000000000000000000000000000000000000000000),
        ),
    ]
